global using System;
global using System.Text;
global using System.Collections.Generic;
global using System.Collections;
global using System.IO;
global using System.Linq;
global using SunamoStringTrim._sunamo.SunamoChar;
global using SunamoStringTrim._sunamo.SunamoChar.Enums;
global using SunamoStringTrim._sunamo.SunamoExceptions;
global using System.Diagnostics;
global using System.Reflection;
global using System.Net;
global using SunamoStringTrim._sunamo;
global using System.Diagnostics.CodeAnalysis;
global using SunamoStringTrim;
global using SunamoStringTrim._sunamo.SunamoStringData;

global using ILogger = Microsoft.Extensions.Logging.ILogger;
global using Microsoft.Extensions.Logging;
global using NullLogger = Microsoft.Extensions.Logging.Abstractions.NullLogger;
