global using System;
global using System.Text;
global using System.Collections.Generic;
global using System.Collections;
global using System.IO;
global using System.Linq;
global using SunamoStringTrim._sunamo.SunamoChar;
global using SunamoStringTrim._sunamo;
global using SunamoStringTrim;
