name: Build SunamoStringTrim

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoStringTrim
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoStringTrim/SunamoStringTrim.csproj

    - name: Build
      run: dotnet build SunamoStringTrim/SunamoStringTrim.csproj --configuration Release --no-restore

  test:
    name: Test SunamoStringTrim.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoStringTrim.Tests/SunamoStringTrim.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoStringTrim.Tests/SunamoStringTrim.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoStringTrim.Tests/SunamoStringTrim.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
